name: Build

on:
  push:
    branches:
      - main
    paths:
      - "Cargo.toml"
      - "src/**"
  pull_request:
    paths:
      - "Cargo.toml"
      - "src/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            label: windows-x86_64
          - runner: macos-latest
            target: x86_64-apple-darwin
            label: macos-x86_64
          - runner: macos-latest
            target: aarch64-apple-darwin
            label: macos-aarch64

    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.94.1
      - uses: swatinem/rust-cache@v2

      - name: Rustup add target
        run: rustup target add ${{ matrix.platform.target }}

      - name: Build target
        run: cargo build --release --target ${{ matrix.platform.target }}

      - uses: actions/upload-artifact@v6
        with:
          name: "meme-generator-contrib-${{ matrix.platform.label }}"
          path: |
            target/${{ matrix.platform.target }}/release/*.dll
            target/${{ matrix.platform.target }}/release/*.dylib

  build_linux:
    runs-on: ${{ matrix.platform.runner }}
    container: ${{ matrix.platform.container }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            container: ghcr.io/memecrafters/meme-generator-build-container:latest
            target: x86_64-unknown-linux-gnu
            label: linux-x86_64
          - runner: ubuntu-24.04-arm
            container: ghcr.io/memecrafters/meme-generator-build-container:arm64
            target: aarch64-unknown-linux-gnu
            label: linux-aarch64

    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.94.1
      - uses: swatinem/rust-cache@v2

      - name: Rustup add target
        run: rustup target add ${{ matrix.platform.target }}

      - name: Build target
        run: cargo build --release --target ${{ matrix.platform.target }}

      - uses: actions/upload-artifact@v6
        with:
          name: "meme-generator-contrib-${{ matrix.platform.label }}"
          path: |
            target/${{ matrix.platform.target }}/release/*.so

  build_android:
    runs-on: ${{ matrix.platform.runner }}
    container: ${{ matrix.platform.container }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            container: ghcr.io/memecrafters/meme-generator-build-container:android
            target: aarch64-linux-android
            label: android-aarch64

    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.94.1
      - uses: swatinem/rust-cache@v2

      - name: Rustup add target
        run: rustup target add ${{ matrix.platform.target }}

      - name: Build target
        run: cargo build --release --target ${{ matrix.platform.target }}

      - uses: actions/upload-artifact@v6
        with:
          name: "meme-generator-contrib-${{ matrix.platform.label }}"
          path: |
            target/${{ matrix.platform.target }}/release/*.so
